// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRNMGVYEMkeeiut5wuUzqPmAfwR6JMmIY',
    appId: '1:962204222268:web:67d7d78db859c795439439',
    messagingSenderId: '962204222268',
    projectId: 'gil-todo-app',
    authDomain: 'gil-todo-app.firebaseapp.com',
    storageBucket: 'gil-todo-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP9bTMxHtJXjLFqUncUNcp1jcGi6b07-g',
    appId: '1:962204222268:android:d4134098852ed832439439',
    messagingSenderId: '962204222268',
    projectId: 'gil-todo-app',
    storageBucket: 'gil-todo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxpze9f2zfk3SHbSTa4A3-8foF8J0zIQ',
    appId: '1:962204222268:ios:c4c8b978da8fb329439439',
    messagingSenderId: '962204222268',
    projectId: 'gil-todo-app',
    storageBucket: 'gil-todo-app.appspot.com',
    iosBundleId: 'com.example.todoListGilApp',
  );
}
